server:
  port: 80
spring:
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Shanghai
  # ehcache
#  cache:
#    ehcache:
#      config: classpath:/a.xml
  cache:
    redis:
      # 进入到期，默认情况下永不过期
      time-to-live: 100s
      key-prefix: pop
#      use-key-prefix: true
#  redis:
#    database:
#    host:
#    port:
#    password:
#    pool:
      # 连接池最大连接数
#      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: -1
      # 连接池最大空闲连接
#      max-idle: 8
      # 连接池最小空闲连接
#      min-idle: 0
      # 连接超时时间（毫秒）
#      timeout: 100
